api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "zip-validation"
type = "function"
uid = "70ca1d57-460b-9f23-6f21-01eb5ea6bda1684456ac"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
